---
driver:
  name: vagrant
  vagrantfiles:
    - Vagrantfile.rb
  synced_folders:
    - ['.','/vagrant']

provisioner:
  name: nodes
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 14.12.3

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
#  - name: centos/7

suites:
  - name: master
    run_list:
      - recipe[apt]
      - recipe[kubeadm::master]
      - recipe[kubeadm::dashboard]
      #- recipe[kubeadm::heapster]
    driver:
      vm_hostname: master.vagrant.test
      network:
        - ["forwarded_port", {guest: 8001, host: 9001}]
        - ["private_network", {ip: "172.28.128.200"}]
      customize:
        memory: 2048
        cpus: 2
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: null
  - name: node01
    run_list:
      - recipe[apt]
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node01.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.201"}]
      customize:
        memory: 2048
        cpus: 2
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node02
    run_list:
      - recipe[apt]
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node02.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.202"}]
      customize:
        memory: 2048
        cpus: 2
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node03
    run_list:
      - recipe[apt]
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node03.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.203"}]
      customize:
        memory: 2048
        cpus: 2
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node04
    run_list:
      - recipe[apt]
      - recipe[kubeadm::node]
    driver:
      vm_hostname: node04.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.204"}]
      customize:
        memory: 2048
        cpus: 2
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
